### ISSUE TITLE
Hide livestream link for non-ticketed

### ISSUE THREAD

**Issue by brianrc** [mt-support/tribe-ext-events-control#6]
Really love the idea of this. Any way to get it to hide the live stream link if the user hasn't purchased a ticket yet?

**Comment by bordoni** [comment]
Currently, that is not part of the Live Stream link piece of this Extension. But we have some other extensions for shortcodes that would allow you to do something very similar to what you are suggesting there.

https://theeventscalendar.com/extensions/event-tickets-shortcodes/

Hopefully, that helps.

**Comment by clintonb** [comment]
It would be helpful to denote this limitation in the readme and marketing docs. Given the current pandemic, many folks are doing paid online events. Your marketing page states that [Events Calendar](https://theeventscalendar.com/wordpress-events-calendar/) supports online events, but that's only the case if folks manage to find this extension, which wasn't as simple as it should be. Having done all of this, and purchased Event Tickets Plus, it's quite frustrating to learn the two don't work well with one another.
